# Generated by Django 5.0.7 on 2025-03-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disaster_app', '0002_foodrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodrequest',
            old_name='contact_number',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='foodrequest',
            old_name='additional_notes',
            new_name='notes',
        ),
        migrations.RemoveField(
            model_name='foodrequest',
            name='number_of_people',
        ),
        migrations.AddField(
            model_name='foodrequest',
            name='people_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='foodrequest',
            name='location',
            field=models.TextField(),
        ),
    ]
