# Generated by Django 5.0.7 on 2025-03-17 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disaster_app', '0006_alter_foodoffer_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodoffer',
            name='user',
        ),
    ]
