# Generated by Django 5.0.7 on 2025-03-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disaster_app', '0007_remove_foodoffer_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisasterReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disaster_type', models.CharField(choices=[('Flood', 'Flood'), ('Earthquake', 'Earthquake'), ('Fire', 'Fire'), ('Tornado', 'Tornado'), ('Other', 'Other')], max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('contact', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='disaster_reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
