# Generated by Django 5.0.7 on 2025-03-18 02:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disaster_app', '0008_disasterreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='disasterreport',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
