# Generated by Django 5.0.7 on 2025-03-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disaster_app', '0009_disasterreport_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('volunteer', 'Volunteer'), ('victim', 'Victim'), ('organization', 'Organization')], default='volunteer', max_length=20)),
                ('availability', models.DateTimeField()),
                ('skills', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
