# Generated by Django 5.0.7 on 2025-03-21 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disaster_app', '0011_financialaidrequest_financialdonation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShelterOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('shelter_address', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
                ('shelter_type', models.CharField(max_length=100)),
                ('sleeping_arrangements', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShelterRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('num_people', models.IntegerField()),
                ('current_location', models.CharField(max_length=255)),
                ('shelter_location', models.CharField(max_length=255)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
