# Generated by Django 5.0.7 on 2025-03-21 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disaster_app', '0012_shelteroffer_shelterrequest'),
    ]

    operations = [
    ]
