# Generated by Django 5.0.7 on 2025-03-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disaster_app', '0013_auto_20250321_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=255)),
                ('issue_type', models.CharField(choices=[('injury', 'Injury'), ('illness', 'Illness'), ('emergency', 'Emergency'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
